# Generated by Django 5.1.4 on 2025-01-03 22:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("user", models.CharField(max_length=255, verbose_name="User ID")),
                ("body_weight", models.FloatField(null=True)),
                ("body_height", models.FloatField(null=True)),
                (
                    "body_type",
                    models.CharField(
                        choices=[
                            ("t", "Thin"),
                            ("s", "Slim"),
                            ("a", "Average"),
                            ("at", "Athletic"),
                            ("m", "Muscular"),
                            ("o", "Overweight"),
                        ],
                        default="a",
                        max_length=255,
                    ),
                ),
                (
                    "activity_level",
                    models.FloatField(
                        choices=[
                            (1.2, "Sedentary"),
                            (1.375, "Lightly Active"),
                            (1.55, "Moderately Active"),
                            (1.7, "Active"),
                            (1.9, "Very Active"),
                            (2.0, "Extra Active"),
                            (4.0, "Extreme Active"),
                        ],
                        default=1.375,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(null=True)),
            ],
            options={
                "verbose_name_plural": "Plans",
                "ordering": ["-start_date"],
                "permissions": [("view_all_plans", "Can view all plans")],
                "unique_together": {("user", "name", "start_date", "end_date")},
            },
        ),
        migrations.CreateModel(
            name="PlanMeal",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField(auto_now_add=True, help_text="Date of the meal plan")),
                ("recipe", models.CharField(max_length=255, verbose_name="Recipe ID")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="meal", to="core.plan"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanProgress",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("weight", models.FloatField()),
                ("log", models.TextField()),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.plan")),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("plan", "date")},
            },
        ),
    ]
